# Generated by Django 5.2.8 on 2026-02-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peluqueros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(default='', max_length=150, verbose_name='Apellido')),
                ('especialidad', models.PositiveSmallIntegerField(verbose_name='Especialidad')),
            ],
        ),
    ]
