# Generated by Django 5.2.8 on 2026-02-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.AlterField(
            model_name='peluqueros',
            name='apellido',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='peluqueros',
            name='especialidad',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Corte y estilismo'), (2, 'Coloración y efectos'), (3, 'Tratamientos y cuidado capilar')], default=1, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='peluqueros',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora', models.TimeField(verbose_name='Hora de la cita')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('peluquero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Principal.peluqueros', verbose_name='Peluquero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Principal.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
