# Generated by Django 5.2.8 on 2026-02-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_categoriaproducto_cita_estado_cliente_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peluqueros',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='peluqueros',
        ),
        migrations.AddField(
            model_name='peluqueros',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='peluqueros', to='Principal.servicio', verbose_name='Servicios que realiza'),
        ),
    ]
