# Generated by Django 5.2.8 on 2026-02-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_remove_peluqueros_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='lineapedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='lineapedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
        migrations.DeleteModel(
            name='LineaPedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
