# Generated by Django 5.2.8 on 2026-02-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0005_remove_producto_categorias_remove_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoPeluquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana (08:00–13:30)'), ('TARDE', 'Tarde (15:00–21:00)'), ('COMPLETO', 'Completo (mañana + tarde)')], max_length=10, verbose_name='Turno')),
                ('activo', models.BooleanField(default=True)),
                ('peluquero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_fecha', to='Principal.peluqueros', verbose_name='Peluquero')),
            ],
            options={
                'verbose_name': 'Turno por fechas',
                'verbose_name_plural': 'Turnos por fechas',
                'ordering': ['-fecha_inicio', 'peluquero'],
                'indexes': [models.Index(fields=['peluquero', 'fecha_inicio', 'fecha_fin'], name='Principal_t_peluque_6661f2_idx')],
            },
        ),
    ]
